app/reports/forms.py
import datetime as datetime

from flask_wtf import Form
from flask_wtf.file import FileField, FileAllowed
from wtforms.fields import (
    SelectField,
    StringField,
    SubmitField,
    IntegerField,
    TextAreaField,
    HiddenField,
    DateField,
    RadioField,
    FieldList,
    BooleanField
)
from wtforms_components import TimeField
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.validators import (
    InputRequired,
    Length,
    Optional,
    NumberRange,
    URL,
    Regexp
)

from app.custom_validators import StrippedLength, ValidLocation, RequiredIf, RequireDescription
from .. import db


class IncidentReportForm(Form):

    address = StringField('Address', validators=[
        InputRequired('Address is required.'),
        ValidLocation()
        ])

    latitude = HiddenField('Latitude')

    longitude = HiddenField('Longitude')

    car = BooleanField('Car', validators=[
        Optional()
    ])

    bus = BooleanField('Bus', validators=[
        Optional()
    ])

    truck = BooleanField('Truck', validators=[
        Optional()
    ])

    bicycle = BooleanField('Bicycle', validators=[
        Optional()
    ])

    pedestrian = BooleanField('Pedestrian', validators=[
        Optional()
    ])

    injuries = RadioField('Did an injury occur?', choices=[
        ('Yes', 'Yes'),
        ('No', 'No')
    ], validators=[InputRequired()])

    injuries_description = TextAreaField('Injuries Description', validators=[
        RequireDescription('injuries'),
        Length(max=5000)
    ])

    witness = RadioField('Did you observe or experience the incident?', choices=[
        ('Observed', 'Observed'),
        ('Experienced', 'Experienced')
    ], validators=[InputRequired()])

    category = SelectField('Category',
                choices=[("Failure to stop", "Failure to stop"),
                        ("Running a red light", "Running a red light"),
                        ("Swerving vehicle", "Swerving vehicle"),
                        ("Tailgating", "Tailgating"),
                        ("Cycling on sidewalk", "Cycling on sidewalk"),
                        ("Car door", "Car door"),
                        ("Crossing against signal", "Crossing against signal"),
                        ("Other", "Other")],
                validators=[
                    InputRequired()
                ])

    description = TextAreaField('Description', validators=[
        Optional(),
        Length(max=5000)
    ])

    road_conditions = TextAreaField('Weather/Road Conditions', validators=[
        Optional(),
        Length(max=5000)
    ])

    today = datetime.datetime.today()

    date = DateField('Date of Event (year-month-day)',
                     default=today.strftime('%m-%d-%Y'),
                     validators=[InputRequired()])

    time = TimeField('Time of Event (hours:minutes am/pm)',
                     default=today.strftime('%I:%M %p'),
                     validators=[InputRequired()])

    picture_file = FileField(
        'Upload a Photo',
        validators=[
            Optional(),
            FileAllowed(['jpg', 'jpe', 'jpeg', 'png', 'gif', 'svg', 'bmp'],
                        'Only images are allowed.')
        ]
    )

    picture_url = StringField('Picture URL', validators=[
                Optional(),
                URL(message='Picture URL must be a valid URL. '
                    'Please upload the image to an image hosting website '
                    'and paste the link here.')
        ])

    deaths = IntegerField('Number of Deaths', validators=[Optional()])

    contact_name = StringField('Contact Name', validators=[
        Optional(),
        Length(max=1000)
    ])

    contact_phone = StringField('Contact Phone', validators=[
        Optional(),
        Length(max=1000)
    ])

    contact_email = StringField('Contact E-mail', validators=[
        Optional(),
        Length(max=100)
    ])

    submit = SubmitField('Create Report')


class EditIncidentReportForm(IncidentReportForm):

    submit = SubmitField('Update Report')

app/reports/__init__.py
from flask import Blueprint

reports = Blueprint('reports', __name__)

from . import views  # noqa

app/reports/views.py
from datetime import datetime

from flask import render_template, abort, flash, redirect, url_for, current_app
from flask_login import login_required, current_user
from flask_rq import get_queue
from werkzeug import secure_filename

from .forms import EditIncidentReportForm

from . import reports
from .. import db
from ..models import Incident
from ..decorators import admin_required
from ..utils import (
    flash_errors,
    geocode,
    parse_timedelta,
    delete_image,
    upload_image,
)


@reports.route('/all')
@login_required
@admin_required
def view_reports():
    """View all idling incident reports.
    Admins can see all reports.
    General users do not have access to this page."""

    if current_user.is_admin():
        incident_reports = Incident.query.all()

    # TODO test using real data
    return render_template('reports/reports.html', reports=incident_reports)

@reports.route('/<int:report_id>')
@reports.route('/<int:report_id>/info')
@login_required
def report_info(report_id):
    """View a report"""
    report = Incident.query.filter_by(id=report_id).first()

    if report is None:
        abort(404)

    # Either the user is looking at their own report, or the user is an admin.
    if not current_user.is_admin():
        abort(403)

    return render_template('reports/manage_report.html', report=report)


@reports.route('/<int:report_id>/edit_info', methods=['GET', 'POST'])
@login_required
def edit_report_info(report_id):
    """Change the fields for a report"""
    report = Incident.query.filter_by(id=report_id).first()

    if report is None:
        abort(404)
    # Either the user is editing their own report, or the user is an admin.
    if not current_user.is_admin():
        abort(403)

    form = EditIncidentReportForm()

    if form.validate_on_submit():

        report.car = form.car.data
        report.bus = form.bus.data
        report.truck = form.truck.data
        report.bicycle = form.bicycle.data
        report.pedestrian = form.pedestrian.data

        lat, lng = geocode(form.address.data)
        report.address.latitude, report.address.longitude = lat, lng
        report.address.original_user_text = form.address.data

        d, t = form.date.data, form.time.data
        report.date = datetime(year=d.year, month=d.month, day=d.day,
                               hour=t.hour, minute=t.minute, second=t.second)

        report.picture_url = form.picture_url.data
        report.category = form.category.data
        report.description = form.description.data
        report.injuries = form.injuries.data
        report.injuries_description = form.injuries_description.data
        report.witness = form.witness.data
        report.road_conditions = form.road_conditions.data
        report.deaths = form.deaths.data
        if (form.deaths.data == None):
            report.deaths = 0

        if form.picture_file.data.filename:
            filepath = secure_filename(form.picture_file.data.filename)
            form.picture_file.data.save(filepath)

            # synchronously upload image so that the user will be able to see
            # the changes immediately.
            link, deletehash = upload_image(
                imgur_client_id=current_app.config['IMGUR_CLIENT_ID'],
                imgur_client_secret=current_app.config['IMGUR_CLIENT_SECRET'],
                app_name=current_app.config['APP_NAME'],
                image_file_path=filepath
            )

            report.picture_url = link
            report.picture_deletehash = deletehash

        report.contact_name = form.contact_name.data
        report.contact_phone = (int(form.contact_phone.data) if len(form.contact_phone.data) > 0 else None)
        report.contact_email = form.contact_email.data

        db.session.add(report)
        db.session.commit()
        flash('Report information updated.', 'form-success')
    elif form.errors.items():
        flash_errors(form)

    # pre-populate form

    if report.witness.lower() == 'observed':
        form.witness.default = 'Observed'
    else:
        form.witness.default = 'Experienced'

    form.address.default = report.address.original_user_text

    form.date.default = report.date
    form.time.default = report.date

    form.picture_url.default = report.picture_url
    form.category.default = report.category
    form.description.default = report.description
    form.injuries.default = report.injuries
    form.injuries_description.default = report.injuries_description
    form.deaths.default = report.deaths
    form.contact_name.default = report.contact_name
    form.contact_phone.default = str(report.contact_phone)
    form.contact_email.default = report.contact_email


    form.process()

    return render_template('reports/manage_report.html', report=report,
                           form=form)


@reports.route('/<int:report_id>/delete')
@login_required
def delete_report_request(report_id):
    """Request deletion of a report."""
    report = Incident.query.filter_by(id=report_id).first()

    if report is None:
        abort(404)

    if not current_user.is_admin():
        abort(403)

    return render_template('reports/manage_report.html', report=report)


@reports.route('/<int:report_id>/_delete')
@login_required
def delete_report(report_id):
    """Delete a report"""

    report = Incident.query.filter_by(id=report_id).first()

    if report.picture_deletehash:
        # Asynchronously delete the report's image
        get_queue().enqueue(
            delete_image,
            deletehash=report.picture_deletehash,
            imgur_client_id=current_app.config['IMGUR_CLIENT_ID'],
            imgur_client_secret=current_app.config['IMGUR_CLIENT_SECRET'],
        )
    # report_user_id = report.user_id

    db.session.delete(report)
    db.session.commit()
    flash('Successfully deleted report.', 'success')

    # TODO - address edge case where an admin clicks on their own report from
    # reports/all endpoint, should redirect back to /all. use cookies
    # if report_user_id == current_user.id:
    #     return redirect(url_for('reports.view_my_reports'))
    # else:
    return redirect(url_for('reports.view_reports'))

app/templates/reports/manage_report.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}

{% set deletion_endpoint = 'reports.delete_report_request' %}

{% if (report.user_id == current_user.id) or current_user.is_admin() %}
    {% set endpoints = [
        ('reports.report_info', 'Report information'),
        ('reports.edit_report_info', 'Edit report'),
        (deletion_endpoint, 'Delete report')
    ] %}
{% else %}
    {% set endpoints = [
        ('reports.report_info', 'Report information'),
    ] %}
{% endif %}

{% macro navigation(items) %}
    <div class="ui vertical fluid secondary menu">
        {% for route, name in items %}
            {% set href = url_for(route, report_id=report.id) %}
            <a class="item {% if request.endpoint == route %}active{% endif %}" href="{{ href }}">
                {{ name }}
            </a>
        {% endfor %}
    </div>
{% endmacro %}

{% macro report_info(report) %}
    <table class="ui compact definition table">
        <tr><td>Address</td><td>{{ report.address }}</td></tr>
        <tr><td>Date</td><td>{{ report.date.strftime('%m-%d-%Y') }}</td></tr>
        <tr><td>Time</td><td>{{ report.date.strftime('%I:%M %p') }}</td></tr>
        <tr><td>Car</td><td>{{ report.car }}</td></tr>
        <tr><td>Bus</td><td>{{ report.bus }}</td></tr>
        <tr><td>Truck</td><td>{{ report.truck }}</td></tr>
        <tr><td>Bicycle</td><td>{{ report.bicycle }}</td></tr>
        <tr><td>Pedestrian</td><td>{{ report.pedestrian }}</td></tr>
        <tr><td>Category</td><td>{{ report.category }}</td><tr>
        <tr><td>Description</td><td>{{ report.description }}</td></tr>
        <tr><td>Weather/Road Conditions</td><td>{{ report.road_conditions }}</td></tr>
        <tr><td>Injuries</td><td>{{ report.injuries }}</td></tr>
        <tr><td>Injuries Description</td><td>{{ report.injuries_description }}</td></tr>
        <tr><td>Observed/Experienced</td><td>{{ report.witness }}</td></tr>
        <tr><td>Number of Deaths</td><td>{{ report.deaths }}</td></tr>
        <tr><td>Picture</td>
            <td>
                {% if report.picture_url %}
                <img src="{{ report.picture_url }}" alt="report picture" width="200">
                {% endif %}
            </td>
        </tr>
        <tr><td>Contact Name</td><td>{{ report.contact_name }}</td></tr>
        <tr><td>Contact Phone</td><td>{{ report.contact_phone }}</td></tr>
        <tr><td>Contact Email</td><td>{{ report.contact_email }}</td></tr>
    </table>
{% endmacro %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">
            <a class="ui basic compact button" href="{{ url_for('reports.view_reports') }}">
                <i class="caret left icon"></i>
                Back to all reports
            </a>
            <h3 class="ui header">
              {% if (report.user) %}
                {{ '%s\'s report' % (report.user.full_name()) }}
              {% endif %}
                <div class="sub header">View and manage this report.</div>
            </h3>
        </div>
        <div class="stretched divided very relaxed row">
            <div class="four wide column">
                {{ navigation(endpoints) }}
            </div>
            <div class="eight wide column">
                {% if request.endpoint == deletion_endpoint %}
                    <h3 class="ui red block header">
                        <i class="warning circle icon"></i>
                        <div class="content">
                            This action is permanent
                            <div class="sub header">
                                Deleting a report is not a reversible change. Any information associated
                                with this report will be removed, and cannot be recovered.
                            </div>
                        </div>
                    </h3>

                    <div class="ui form">
                        <div class="inline field">
                            <div class="ui deletion checkbox">
                                <input type="checkbox" tabindex="0" class="hidden">
                                <label>I understand that this action cannot be undone.</label>
                            </div>
                        </div>
                        <a class="ui disabled negative deletion button">
                            Delete this report
                        </a>
                    </div>
                    </div>
                {% elif form %}
                    {% set flashes = {
                    'error': get_flashed_messages(category_filter=['form-error']),
                    'warning': get_flashed_messages(category_filter=['form-check-email']),
                    'info': get_flashed_messages(category_filter=['form-info']),
                    'success': get_flashed_messages(category_filter=['form-success'])
                    } %}
                    {{ f.begin_form(form, flashes) }}
                    {{ f.render_form_field(form.witness)}}
                    {{ f.render_form_field(form.date)}}
                    {{ f.render_form_field(form.time)}}
                    {{ f.render_form_field(form.address) }}
                    {{ f.render_form_field(form.car) }}
                    {{ f.render_form_field(form.bus) }}
                    {{ f.render_form_field(form.truck) }}
                    {{ f.render_form_field(form.bicycle) }}
                    {{ f.render_form_field(form.pedestrian) }}
                    {{ f.render_form_field(form.category) }}
                    {{ f.render_form_field(form.description) }}
                    {{ f.render_form_field(form.injuries)}}
                    {{ f.render_form_field(form.injuries_description)}}
                    {{ f.render_form_field(form.road_conditions) }}
                    {{ f.render_form_field(form.deaths) }}
                    {{ f.render_form_field(form.picture_file) }}
                    {{ f.render_form_field(form.contact_name)}}
                    {{ f.render_form_field(form.contact_phone)}}
                    {{ f.render_form_field(form.contact_email)}}
                    {% for field in form | selectattr('type', 'equalto', 'SubmitField') %}
                    {{ f.render_form_field(field) }}
                    {% endfor %}
                    {{ form.hidden_tag() }}
                    {{ f.end_form() }}
                {% else %}
                    {{ report_info(report) }}
                {% endif %}
            </div>
        </div>
    </div>

    <script type="text/javascript">
        $(document).ready(function() {
            $('.deletion.checkbox').checkbox({
                onChecked: function() {
                    $('.deletion.button').removeClass('disabled')
                        .attr('href', '{{ url_for('reports.delete_report', report_id=report.id) }}');
                },
                onUnchecked: function() {
                    $('.deletion.button').addClass('disabled').removeAttr('href');
                }
            });
            console.log("{{ report.pedestrian }}" === "True");
            if ("{{ report.car }}" === "False") {
                $("#car").prop("checked", false);
            }
            if ("{{ report.bus }}" === "False") {
                $("#bus").prop('checked', false);
            }
            if ("{{ report.truck }}" === "False") {
                $("#truck").prop("checked", false);
            }
            if ("{{ report.bicycle }}" === "False") {
                $("#bicycle").prop("checked", false);
            }
            if ("{{ report.pedestrian }}" === "False") {
                $("#pedestrian").prop("checked", false);
            }
            $('#car').value = ("{{ report.car }}" === "True") ? "y" : "n";
            $('#bus').value = ("{{ report.bus }}" === "True") ? "y" : "n";
            $('#truck').value = ("{{ report.truck }}"=== "True") ? "y" : "n";
            $('#bicycle').value = ("{{ report.bicycle }}" === "True") ? "y" : "n";
            $('#pedestrian').value = ("{{ report.pedestrian }}" === "True") ? "y" : "n";
        });
    </script>
{% endblock %}

app/templates/reports/reports.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="ui stackable grid container">
        <div class="sixteen wide tablet twelve wide computer centered column">
            <a class="ui basic compact button" href="{{ url_for('admin.index') }}">
                <i class="caret left icon"></i>
                <!-- TODO: change dashboard link for general and agency worker users -->
                Back to dashboard
            </a>

            <div class="ui two column vertically padded stackable grid">
              <div class="column">
                  <h2 class="ui header">
                    Incident Reports
                      <div class="sub header">
                        View and manage idling incident reports.
                      </div>
                  </h2>
              </div>
              <div class="computer only right aligned column">
                  <div class="ui icon input">
                      <input class="search-reports" type="text" placeholder="Search reports…">
                      <i class="search icon"></i>
                  </div>
              </div>
              <div class="mobile tablet only column">
                  <div class="ui icon input">
                      <input class="search-reports" type="text" placeholder="Search reports…">
                      <i class="search icon"></i>
                  </div>
              </div>
            </div>

            {# Use overflow-x: scroll so that mobile views don't freak out
             # when the table is too wide #}
            <div style="overflow-x: scroll;">
                <table class="ui searchable sortable unstackable selectable celled table">
                    <thead>
                        <tr>
                            <th class="sorted descending">Date</th>
                            <th>Address</th>
                            <th>Car</th>
                            <th>Bus</th>
                            <th>Truck</th>
                            <th>Bicycle</th>
                            <th>Pedestrian</th>
                            <th>Category</th>
                            <th>Description</th>
                            <th>Weather/Road Conditions</th>
                            <th>Injuries</th>
                            <th>Injuries Description</th>
                            <th>Observed/Experienced</th>
                            <th>Number of Deaths</th>
                            <th>Picture URL</th>
                            <th>Contact Name</th>
                            <th>Contact Phone</th>
                            <th>Contact Email</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for r in reports | sort(reverse=True, attribute='date') %}
                        <tr onclick="window.location.href = '{{ url_for('reports.report_info', report_id=r.id) }}';">
                            <td class="single line">{{ r.date.strftime('%Y-%m-%d at %I:%M %p') }}</td>
                            <td>{{ r.address }}</td>
                            <td>{{ r.car }}</td>
                            <td>{{ r.bus }}</td>
                            <td>{{ r.truck }}</td>
                            <td>{{ r.bicycle }}</td>
                            <td>{{ r.pedestrian }}</td>
                            <td>{{ r.category }}</td>
                            <td>{{ r.description }}</td>
                            <td>{{ r.road_conditions }}</td>
                            <td>{{ r.injuries }}</td>
                            <td>{{ r.injuries_description }}</td>
                            <td>{{ r.witness }}</td>
                            <td>{{ r.deaths }}</td>
                            <td>{{ r.picture_url }}</td>
                            <td>{{ r.contact_name }}</td>
                            <td>{{ r.contact_phone }}</td>
                            <td>{{ r.contact_email }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            $('.search-reports').keyup(function () {
                var searchText = $(this).val();
                if (searchText.length > 0) {
                    $('tbody td:icontains(' + searchText + ')').addClass('positive');
                    $('td.positive').not(':icontains(' + searchText + ')').removeClass('positive');
                    $('tbody td').not(':icontains(' + searchText + ')').closest('tr').addClass('hidden').hide();
                    $('tr.hidden:icontains(' + searchText + ')').removeClass('hidden').show();
                } else {
                    $('td.positive').removeClass('positive');
                    $('tr.hidden').removeClass('hidden').show();
                }
            });
        });
    </script>
{% endblock %}